#!/usr/bin/env bash
# Usage: powprox setup
# Summary: Sets up Nginx -> Pow proxy and prepares SSL certificates
# Help: This is safe to run anytime. It'll pick up where it left off.
# It'll install Nginx (if it isn't already), set up Pow proxy config
# (if it isn't already, etc…), create a root certificate authority,
# trust it in the Keychain, generate an SSL cert for all Pow domains,
# and configure Nginx to run as root (to bind privileged ports 80 & 443).
set -e
[ -n "$POWPROX_DEBUG" ] && set -x

is_nginx_installed() {
  type -p nginx >/dev/null && \
    (nginx -V 2>&1 | grep -q 'built with OpenSSL 1\.\([^0]\|0\.[^0]\)') && \
    (nginx -V 2>&1 | grep -q 'with-http_spdy_module' )
}

install_nginx() {
  # We need homebrewed OpenSSL for NPN support and TLS 1.1+
  brew install openssl
  brew install --with-spdy
}

generate_nginx_config() {
  mkdir -p "$POWPROX_DIR/nginx"

  dest="$POWPROX_DIR/nginx/nginx.conf"
  old="${dest}.old"

  [ -f "$dest" ] && mv "$dest" "${old}"

  powprox-generate-nginx-config > "$dest"

  if [ -f "$old" ]; then
    if ! diff -q "$old" "$dest" >/dev/null; then
      echo "Generated new Nginx config. Differences from the old config:"
      diff -u "$old" "$dest" || true
    fi
  else
    echo "Generated new Nginx config."
  fi

  rm -rf "$POWPROX_DIR/nginx/sites"
  mkdir "$POWPROX_DIR/nginx/sites"
  local IFS=$'\n'
  for host_path in $(powprox-list-pow-hosts --paths); do
    host_conf_path="$host_path/config/powprox/nginx.conf"

    # Link optional per-site Nginx config
    if [ -f "$host_conf_path" ]; then
      # Use a content digest as link name to ensure unique config links.
      # That allows us to symlink sites in ~/.pow to each other as aliases
      # without duplicating nginx config.
      if ln -s "$host_conf_path" "$POWPROX_DIR/nginx/sites/$(md5 -q "$host_conf_path")" 2>/dev/null; then
        echo "Linked site config: ${host_path##*/}"
      else
        echo "Skipped site config: ${host_path##*/} (already linked by another site)"
      fi
    fi

    # Touch tmp/powprox.enabled to tell the app that Powprox is proxying it.
    # Touch tmp/restart.txt to tell Pow to restart the app, allowing it to
    # see that Powprox is enabled.
    if [ -d "$host_path" ]; then
      mkdir -p "$host_path/tmp"
      touch "$host_path/tmp/powprox.enabled" "$host_path/tmp/restart.txt"
    fi
  done

  ln -sf "$dest" /usr/local/etc/nginx/servers/powprox.conf

  echo "Checking Nginx config…"
  sudo nginx -t
}

nginx_launchdaemon() {
  if [ -f ~/Library/LaunchDaemons/homebrew.mxcl.nginx.plist ]; then
    launchctl unload ~/Library/LaunchDaemons/homebrew.mxcl.nginx.plist >/dev/null 2>&1
    rm ~/Library/LaunchDaemons/homebrew.mxcl.nginx.plist
  fi

  if [ -f /Library/LaunchDaemons/homebrew.mxcl.nginx.plist ]; then
    sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist >/dev/null 2>&1
  fi

  sudo cp /usr/local/opt/nginx/homebrew.mxcl.nginx.plist /Library/LaunchDaemons/
  sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
}

nginx_selftest() {
  echo -n "Pow: "
  curl -H host:pow http://127.0.0.1:20559/status.json
  echo
  echo -n "Nginx: "
  curl -H host:pow http://127.0.0.1/status.json
  echo
}

install_pow_reloader() {
  generate-hostwatcher-launchagent
  launchctl unload "$HOME/Library/LaunchAgents/com.basecamp.powprox.hostwatcher.plist" >/dev/null 2>&1
  launchctl load "$HOME/Library/LaunchAgents/com.basecamp.powprox.hostwatcher.plist"

  generate-nginxreloader-launchdaemon
  sudo launchctl unload /Library/LaunchDaemons/com.basecamp.powprox.nginxreloader.plist >/dev/null 2>&1
  sudo launchctl load /Library/LaunchDaemons/com.basecamp.powprox.nginxreloader.plist
}

powprox-create-server-certificate

echo -n "Checking for Nginx… "
if is_nginx_installed; then
  echo "installed with SPDY support."
else
  echo "not installed with SPDY support."
  install_nginx
fi

echo "Removing Pow's port-forwarding rule"
sudo launchctl unload -w /Library/LaunchDaemons/cx.pow.firewall.plist >/dev/null 2>&1
sudo pfctl -a 'com.apple/250.PowFirewall' -F nat

generate_nginx_config

echo "Launching Nginx"
nginx_launchdaemon

echo "Nginx self-test… "
nginx_selftest

echo "Installing ~/.pow watcher"
install_pow_reloader

echo "Done. Ready to roll!"
