#!/usr/bin/env bash
# Generate list of Pow domains (e.g. .dev, .test, …)
set -e
[ -n "$POWPROX_DEBUG" ] && set -x

eval $(powprox-print-pow-config)

{ echo "$POW_DOMAINS" "$POW_EXT_DOMAINS"
} | tr ',' '\n'
