#!/usr/bin/env bash
# Generate list of Pow hosts in ~/.pow/
set -e

# Get POW_HOST_ROOT
eval $(powprox-print-pow-config)

IFS=
shopt -s nullglob
for host in "$POW_HOST_ROOT"/*; do
  if [ "$1" = "--paths" ]; then
    echo "$host"
  else
    echo "${host##*/}"
  fi
done
