#!/usr/bin/env ruby
require 'erb'
require 'yaml'

root = ENV['_POWPROX_ROOT']
template_path = "#{root}/share/powprox/nginx.conf.erb"
abort "Missing nginx config template: #{template_path}" unless File.file?(template_path)

# Parse Pow config to figure out its listen port and domains
pow_config = Hash[`powprox-print-pow-config`.scan(/^(POW_[^=]+)='([^']+)'$/)]

# Local variables for ERB template
powprox_dir = ENV.fetch('POWPROX_DIR')
ssl_certificate = "#{powprox_dir}/ssl/certs/pow-server.crt"
ssl_certificate_key = "#{powprox_dir}/ssl/certs/pow-server.key"
pow_http_port = pow_config.fetch('POW_HTTP_PORT').to_i
pow_dns_port = pow_config.fetch('POW_DNS_PORT').to_i
pow_domains = pow_config.fetch('POW_DOMAINS').split(',') +
  pow_config['POW_EXT_DOMAINS'].to_s.split(',')
pow_host_root = pow_config.fetch('POW_HOST_ROOT')

print ERB.new(File.read(template_path)).result
