#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export POWPROX_DEBUG=1
  shift
fi

if [ -n "$POWPROX_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _POWPROX_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

if [ -z "${POWPROX_DIR}" ]; then
  POWPROX_DIR="${HOME}/.powprox"
else
  POWPROX_DIR="${POWPROX_DIR%/}"
fi
export POWPROX_DIR

command="$1"
case "$command" in
"" )
  exec powprox-default
  ;;
"-h" | "--help" )
  exec powprox-help
  ;;
* )
  command_path="$(command -v "powprox-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "powprox: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
